language: node_js
node_js:
      - "node"
addons:
  chrome: stable
sudo: required
before_script:
      - npm install
      - npm install -g codecov
      - npm run build
script:
    - npm run test
    - codecov
